language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install blender
install:
  - mkdir tmp && cd tmp
  - wget http://mirror.cs.umn.edu/blender.org/release/Blender2.74/blender-2.74-linux-glibc211-x86_64.tar.bz2
  - tar jxf blender-2.74-linux-glibc211-x86_64.tar.bz2
  - mv blender-2.74-linux-glibc211-x86_64 blender
  - rm blender-2.74-linux-glibc211-x86_64.tar.bz2
  - cd ..
  - sudo ln -s ${PWD}/blender_25/io_xplane2blender ${PWD}/tmp/blender/2.74/scripts/addons/io_xplane2blender
script: cd blender_25 && python tests.py ../tmp/blender/blender
